# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Executar testes no cypress

on:
  #executa sempre que fizer uma alteração na branch master
  push:
    branches: [master]

jobs:
  build:
    #maquina onde será executado
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #vai executar a quantidade de vezes, de acordo com as versões abaixo
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: $(npm bin)/cypress open

